USE SistemaGestionBisblick;

INSERT INTO Informe_Becado (ID_Informe, ID_Becado, Informe_Marzo_Abril, Informe_Julio_Agosto, Informe_Noviembre_Diciembre, Comentario) VALUES
(1, 1, 'Buen desempeño académico', 'Participación en actividades', 'Preparación para exámenes', 'Muy comprometido'),
(2, 2, 'Asistencia irregular', 'Mejoras en actitud', 'Resultados satisfactorios', 'Necesita apoyo'),
(3, 3, 'Destacada participación', 'Incremento en habilidades', 'Cumplimiento de objetivos', 'Muy motivado'),
(4, 4, 'Retraso en entregas', 'Mejoras visibles', 'Seguimiento constante', 'Requiere supervisión'),
(5, 5, 'Excelente rendimiento', 'Participación activa', 'Graduado', 'Ejemplo a seguir'),
(6, 6, 'Compromiso bajo', 'Mejoras en compromiso', 'Resultados mixtos', 'Necesita motivación'),
(7, 7, 'Participación destacada', 'Crecimiento académico', 'Preparación para titulación', 'Muy responsable'),
(8, 8, 'Faltas frecuentes', 'Mejoras en asistencia', 'Resultados aceptables', 'Debe esforzarse más'),
(9, 9, 'Buen rendimiento', 'Participación en eventos', 'Graduado con honores', 'Ejemplar'),
(10, 10, 'Dificultades académicas', 'Apoyo constante', 'Mejoras visibles', 'Requiere ayuda'),
(11, 11, 'Crecimiento constante', 'Resultados positivos', 'Preparación para examen final', 'Muy activo'),
(12, 12, 'Excelente rendimiento', 'Participación en talleres', 'Graduado', 'Ejemplo'),
(13, 13, 'Compromiso irregular', 'Mejoras en desempeño', 'Resultados aceptables', 'Puede mejorar'),
(14, 14, 'Participación destacada', 'Incremento de habilidades', 'Preparación para titulación', 'Muy responsable'),
(15, 15, 'Ausencias frecuentes', 'Mejoras en asistencia', 'Seguimiento necesario', 'Debe esforzarse'),
(16, 16, 'Buen desempeño', 'Participación activa', 'Graduado', 'Ejemplo a seguir'),
(17, 17, 'Compromiso bajo', 'Mejoras en compromiso', 'Resultados mixtos', 'Necesita motivación'),
(18, 18, 'Participación destacada', 'Crecimiento académico', 'Preparación para titulación', 'Muy responsable'),
(19, 19, 'Asistencia irregular', 'Mejoras visibles', 'Resultados satisfactorios', 'Debe esforzarse más'),
(20, 20, 'Buen desempeño', 'Participación activa', 'Graduado', 'Ejemplo a seguir'),
(21, 21, 'Compromiso irregular', 'Mejoras en desempeño', 'Resultados aceptables', 'Puede mejorar'),
(22, 22, 'Participación destacada', 'Incremento de habilidades', 'Preparación para titulación', 'Muy responsable'),
(23, 23, 'Ausencias frecuentes', 'Mejoras en asistencia', 'Seguimiento necesario', 'Debe esforzarse'),
(24, 24, 'Buen desempeño', 'Participación activa', 'Graduado', 'Ejemplo a seguir'),
(25, 25, 'Compromiso bajo', 'Mejoras en compromiso', 'Resultados mixtos', 'Necesita motivación'),
(26, 26, 'Participación destacada', 'Crecimiento académico', 'Preparación para titulación', 'Muy responsable'),
(27, 27, 'Asistencia irregular', 'Mejoras visibles', 'Resultados satisfactorios', 'Debe esforzarse más'),
(28, 28, 'Buen desempeño', 'Participación activa', 'Graduado', 'Ejemplo a seguir');