USE SistemaGestionBisblick;

INSERT INTO DatosLaborales (ID_Laboral, Ocupacion, Ubicacion, Puesto, CargaHoraria, Busqueda_Laboral, LinkedIn, ID_Becado) VALUES
(1, 'Si', 'Buenos Aires', 'Asistente', 'FullTime', 'No', 'https://linkedin.com/in/juanperez', 1),
(2, 'No', NULL, NULL, NULL, 'Si', NULL, 2),
(3, 'Si', 'Rosario', 'Analista', 'PartTime', 'No', 'https://linkedin.com/in/carloslopez', 3),
(4, 'Si', 'Mendoza', 'Técnico', 'Rotativo', 'No', 'https://linkedin.com/in/lauramartinez', 4),
(5, 'No', NULL, NULL, NULL, 'Si', NULL, 5),
(6, 'Si', 'La Plata', 'Supervisor', 'FullTime', 'No', 'https://linkedin.com/in/anafernandez', 6),
(7, 'No', NULL, NULL, NULL, 'Si', NULL, 7),
(8, 'Si', 'Paraná', 'Coordinador', 'PartTime', 'No', 'https://linkedin.com/in/sofiagonzalez', 8),
(9, 'No', NULL, NULL, NULL, 'Si', NULL, 9),
(10, 'Si', 'San Juan', 'Desarrollador', 'FullTime', 'No', 'https://linkedin.com/in/luciaromero', 10),
(11, 'No', NULL, NULL, NULL, 'Si', NULL, 11),
(12, 'Si', 'Posadas', 'Analista', 'PartTime', 'No', 'https://linkedin.com/in/camila.vega', 12),
(13, 'Si', 'Formosa', 'Técnico', 'Rotativo', 'No', 'https://linkedin.com/in/federicocastro', 13),
(14, 'No', NULL, NULL, NULL, 'Si', NULL, 14),
(15, 'Si', 'San Luis', 'Supervisor', 'FullTime', 'No', 'https://linkedin.com/in/pablomendoza', 15),
(16, 'Si', 'Río Gallegos', 'Coordinador', 'PartTime', 'No', 'https://linkedin.com/in/valeriaalvarez', 16),
(17, 'No', NULL, NULL, NULL, 'Si', NULL, 17),
(18, 'Si', 'San Miguel', 'Desarrollador', 'FullTime', 'No', 'https://linkedin.com/in/florenciamora', 18),
(19, 'No', NULL, NULL, NULL, 'Si', NULL, 19),
(20, 'Si', 'La Rioja', 'Asistente', 'PartTime', 'No', 'https://linkedin.com/in/gabrielapaz', 20),
(21, 'Si', 'Santa Fe', 'Técnico', 'FullTime', 'No', 'https://linkedin.com/in/lucasortiz', 21),
(22, 'No', NULL, NULL, NULL, 'Si', NULL, 22),
(23, 'Si', 'Córdoba', 'Analista', 'Rotativo', 'No', 'https://linkedin.com/in/tomasfigueroa', 23),
(24, 'No', NULL, NULL, NULL, 'Si', NULL, 24),
(25, 'Si', 'Mendoza', 'Supervisor', 'FullTime', 'No', 'https://linkedin.com/in/ezequielcampos', 25),
(26, 'No', NULL, NULL, NULL, 'Si', NULL, 26),
(27, 'Si', 'Paraná', 'Coordinador', 'PartTime', 'No', 'https://linkedin.com/in/javierbenitez', 27),
(28, 'Si', 'Neuquén', 'Analista', 'FullTime', 'No', 'https://linkedin.com/in/sabrinacruz', 28);